routes/web.php
<?php

use App\Http\Controllers\CampaignController;

// Route::get('/', function () {
//     return view('auth.login');
// });

// Route::get('/test', [
// 	'uses' => 'TestController@index'
// 	]);

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', [
	'uses' => 'HomeController@getDashboard',
	'as' => 'dashboard',
	'middleware' => 'auth'
	]);

// Dashboard section
Route::get('/home', [
	'uses' => 'HomeController@getDashboard',
	'as' => 'dashboard',
	'middleware' => 'auth'
	]);

Route::get('/dashboard', [
	'uses' => 'HomeController@getDashboard',
	'as' => 'dashboard',
	'middleware' => 'auth'
	]);

// Route::get('/campaign/add',[
// 	'uses' => 'CampaignController@add',
// 	'as' => 'campaign',
// 	'middleware' => 'auth'
// ]);

// Route::post('/campaign/create',[
// 	'uses' => 'CampaignController@create',
// 	'as' => 'campaign',
// 	'middleware' => 'auth'	
// ]);

Route::get('/campaign/archive',[
	'uses' => 'CampaignController@archive',
	'as' => 'campaignarchive',
	'middleware' => 'auth'
]);

Route::resource('campaign','CampaignController');

Route::resource('users','UserController');

// Route::get('/users',[
// 	'uses' => 'UserController@index',
// 	'as' => 'campaign',
// 	'middleware' => 'auth'
// ]);	

// Route::get('/profile',[
// 	'uses' => 'UserController@profile',
// 	'as' => 'profile',
// 	'middleware' => 'auth'
// ]);

Route::get('/report', function () {
    return view('dashboard.report.commingsoon');
});

app/Campaign.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Campaign extends Model
{
    //
    protected $fillable = [
        'user_id', 'campaign_name', 'msresult_id', 'msstatus_id', 'msresponse_id', 'qty', 'notes',
    ];

    // public function number()
    // {
    //     return $this->hasMany(Number::class);
    // }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function campaignresult()
    {
        return $this->belongsTo(Campaignresult::class);
    }    
}

app/Http/Controllers/CampaignController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Number;
use App\Campaign;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class CampaignController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
			$result = Campaign::where('msstatus_id',[1,3])->orderBy('id','DESC')->get();
			return view('dashboard.campaign.index',[
				'page'=>'Campaigns Active',
				'page_title' => 'Dasboard - Campaign',
				'campaign' => $result
			]);
    }			

		public function archive()
		{
			$result = Campaign::where('msstatus_id',2)->orderBy('id','DESC')->get();
			return view('dashboard.campaign.index',[
				'page'=>'Campaigns Archive',
				'page_title' => 'Dasboard - Campaign',
				'campaign' => $result
			]);			
		}

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

		public function add(){
			return view('dashboard.campaign.add',[
				'page' => 'Campaign',
				'page_title' => 'Add',
			]);
		}

    public function create(Request $request)
    {
			return view('dashboard.campaign.add',[
				'page' => 'Campaign',
				'page_title' => 'Add',
			]);
		}

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

			$validator = Validator::make($request->all(), [
				'campaign_name' => 'required|unique:campaigns|min:4|max:255',
			]);
      
			if ($validator->fails()) {
					return redirect('campaign/add')
											->withErrors($validator)
											->withInput();
			}

			$filename = $request->file_nomor;

			$i = 0;
			$data = Array();
			$file = json_decode($filename,true);
			
			if($file == null){
				return redirect('/campaigns')->with('warning','Failed to upload number, the file has to be .XLS!');				
			}

			foreach($file as $f){
				$i++;
				$data[$i] = $f;
			}
			$countdata = count($data);
			
			$validatedData['campaign_name'] = $request->campaign_name;
			$validatedData['user_id'] = auth()->user()->id;
			$validatedData['msstatus_id'] = 1;
			$validatedData['msresult_id'] = 1;
			$validatedData['qty'] = $i;
      		$validatedData['notes'] = '';

			Campaign::create($validatedData);

			$get = Campaign::orderBy('created_at', 'desc')->first();

			$campaign_id = $get->id;
			$insert_number = Array();

			foreach($data as $d){
					$number = [
						'account_id' => auth()->user()->id,
						'campaign_id' => $campaign_id,
						'action' => 0,
						'response' => null, 
						'name' => $d['name'],
						'phone' => $d['phone'],
						'bill_date' => $d['bill_date'],
						'due_date' => $d['due_date'],
						'nominal' => $d['nominal'],
						'call_dial' => null, 
						'call_connect' => null, 
						'call_disconnect' => null, 
						'call_duration' => null, 
					];

					$insert_number[] = $number;
				}

				$removefirst = array_shift($insert_number);	
				$insert_number = collect($insert_number);
				$chunks = $insert_number->chunk(200);
				foreach ($chunks as $chunk)
				{
					 DB::table('numbers')->insert($chunk->toArray());
				}				
			return redirect('/campaign')->with('success','New campaign has been added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\campaign  $campaign
     * @return \Illuminate\Http\Response
     */

    public function show($id)
    {
			// return $id;
			$count_number = DB::table('numbers')->orderBy('status_id','DESC')->where('campaign_id',$id)->count();
			$campaign = Campaign::with('user')->with('campaignresult')->find($id);
			$numbers = Number::with('campaign')->where('campaign_id',$id)->get();
			return view('dashboard.campaign.detail',[
				'page'=>'Campaigns',
				'campaign' => $campaign,
				'total_number' => $count_number,
				'numbers' => $numbers,
			]);
		}	

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\campaign  $campaign
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\campaign  $campaign
     * @return \Illuminate\Http\Response
     */
    public function update($id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\campaign  $campaign
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
			// return $id;
			$button = $request->activebtn;
			// dd($button);
			if($button == 1){
				$params['msstatus_id'] = '2';
				$result = Campaign::where('id',$id)->update($params);
				if($result){
					$color = 'success';
					$message = 'Campaign has been deactivate!';
				} else {
					$color = 'success';
					$message = 'Campaign on ready or pause position';
				}
				return redirect('/campaign')->with($color,$message);
			} else {
				$params['msstatus_id'] = '1';
				Campaign::where('id',$id)->update($params);
				return redirect('/campaign')->with('success','Campaign has been activated!');
			}
    }

		public function runcampaign()
		{
			dd('Run Campaign');
		}
}

resources/views/dashboard/campaign/add.blade.php
@extends('layouts.master')
@push('js')
<script lang="javascript" src="{{ asset('js/xlsx.full.min.js') }}"></script>
@endpush
@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-10 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">New Campaign
          <a href="{{ url ('campaign') }}" class="pull-right" data-toggle="tooltip" title="Cancel add new"><i class="fa fa-close"></i> Cancel</a>
      </div>
      <div class="panel-body">
        <form class="form-horizontal" method="POST" action="{{ action('CampaignController@store') }}">
          {{ csrf_field() }}
          <div class="form-group{{ $errors->has('campaign_name') ? ' has-error' : '' }}">
              <label for="campaign_name" class="col-md-4 control-label">Campaign Name</label>
              <a href="/download/sampleNumberImport.xlsx" type="button" class="btn btn-primary btn-sm" data-toggle="tooltip" title="Sample Data"><i class="fa fa-download"></i></a>
              
              <div class="col-md-6">
                  <input id="campaign_name" type="text" class="form-control" name="campaign_name" value="{{ old('campaign_name') }}" required autofocus>

                  @if ($errors->has('campaign_name'))
                      <span class="help-block">
                          <strong>{{ $errors->first('campaign_name') }}</strong>
                      </span>
                  @endif  
              </div> 
          </div>
          <div class="form-group">
            <label for="name" class="col-md-4 control-label">Insert .xls file</label>
            <div class="col-md-6">
              <div class="input-group">
                <div class="wrapper">
                  <input class="form-control" type="file" id="excel_file" name="excel_file" value="{{ old('excel_file') }}" />
                </div>
              </div>
            </div>
          </div>            
          <div class="form-group">
            <div class="col-md-6 col-md-offset-4">
                <input type="hidden" id='file_nomor' name="file_nomor">
                <button type="submit" class="btn btn-sm btn-primary">Create</button>
                <a href="{{ url('/campaign') }}" class="btn btn-sm btn-warning">Cancel</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

    <div class="col-md-10 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading box-tools">
          Numbers Preview<br />
          {{-- <label class="small" for="">You can't change data in preview, please change in your Excel file</label> --}}
        </div>
        <div class="panel-body">           
          {{-- <div id="unique_data" class="mt-2 mb-4"></div> --}}
          {{-- <div id="excel_data" class="table mt-3"></div>     --}}

          {{-- <div class="mb-2"><span class="h5">Duplikat nomor</span></div>
          
          <div class="table table-responsive">
            <table class="table table-bordered table-striped">
              <thead></thead>
              <tbody id="unique_data"></tbody>
            </table>
          </div> --}}

          <div class="col-lg-12 table-responsive" style="max-height:500px; width: 100%;">
            <table class="table table-bordered table-striped table-condensed">
              <thead class="thead-dark">
                <th>No</th>
                <th>Acc Id</th>
                <th>Nama</th>
                <th>Phone</th>
                <th>Bill Date</th>
                <th>Due Date</th>
                <th>Nominal</th>
              </thead>
              <tbody id="excel_data"></tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@push('scripts')
<script>
  const excel_file = document.getElementById('excel_file');
  excel_file.addEventListener('change', (event) => {
      if(!['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel'].includes(event.target.files[0].type))
      {
          document.getElementById('excel_data').innerHTML = '<div class="alert alert-danger">Only .xlsx or .xls file format are allowed</div>';
          excel_file.value = '';
          return false;
      }
      var reader = new FileReader();
      reader.readAsArrayBuffer(event.target.files[0]);
      reader.onload = function(event){
          var data = new Uint8Array(reader.result);
          var work_book = XLSX.read(data, {type:'array'});
          var sheet_name = work_book.SheetNames;
          var sheet_data = XLSX.utils.sheet_to_json(work_book.Sheets[sheet_name[0]], {header:1,raw:false,cellDates:true,dateNF:'YYYY/mm/dd h:mm:ss'});

          console.log("start");
          // console.log(sheet_data);

          var newarr = Array();

          if(sheet_data.length > 0){
            for(var rowarr = 0; rowarr < sheet_data.length; rowarr++)
              {
                for(cellarr=1;cellarr < sheet_data[rowarr].length;cellarr++){
                  newarr[rowarr] = sheet_data[rowarr][2].replace(/^0+/, '');
                }
              }
          }

          // console.log(newarr);

          const yourArray = newarr

          let duplicates = []

          const tempArray = [...yourArray].sort()

          for (let i = 0; i < tempArray.length; i++) {
            if (tempArray[i + 1] === tempArray[i]) {
              duplicates.push(tempArray[i])
            }
          }

          function uniqueArray2(arr) {
              var a = [];
              for (var i=0, l=arr.length; i<l; i++)
                  if (a.indexOf(arr[i][2]) === -1 && arr[i][2] !== '')
                      a.push(arr[i]);
              return a;
          }
          sort_data = uniqueArray2(sheet_data);

          var arrayWithDuplicates = sheet_data

          function removeDuplicates(originalArray, prop) {
              var newArray = [];
              var lookupObject  = {};

              for(var i in originalArray) {
                  lookupObject[originalArray[i][prop]] = originalArray[i];
              }

              for(i in lookupObject) {
                newArray.push(lookupObject[i]);
              }
                return newArray;
          }

          var uniqueArray = removeDuplicates(arrayWithDuplicates, "2");
          sheet_data_clean = uniqueArray;

          // console.log(sheet_data_clean);

          var jsonObj = {};
          for (var i = 0 ; i < uniqueArray.length; i++) {
              jsonObj[(i+1)] = uniqueArray[i];
          }

          var offset = -8;
          var newdate = new Date();
          
          console.log(newdate);

          format = function date2str(x, y) {
              var z = {
                  M: x.getMonth() + 1,
                  d: x.getDate(),
                  h: x.getHours(),
                  m: x.getMinutes(),
                  s: x.getSeconds()
              };
              y = y.replace(/(M+|d+|h+|m+|s+)/g, function(v) {
                  return ((v.length > 1 ? "0" : "") + z[v.slice(-1)]).slice(-2)
              });

              return y.replace(/(y+)/g, function(v) {
                  return x.getFullYear().toString().slice(-v.length)
              });
          }          
          
          var datenow = format(newdate, 'yyyy/mm/dd h:m:s')

          var data = uniqueArray;
          var json = data.map(function (value, key) {
              return {
                  'account_id': {{ auth()->user()->id }},
                  'account_id': value[0],
                  'name': value[1],
                  'phone': parseInt(value[2]),
                  'bill_date': value[3],
                  'due_date': value[4],
                  'nominal': value[5],
              }
          });

          // console.log(json)
          console.log(JSON.stringify(json));

          $("#file_nomor").val(JSON.stringify(json));

        t_unique = "";
          var table_output = '<tr><td colspan="7"></td></tr>';
          for(var row = 1; row < sheet_data_clean.length; row++)
          {
            $num = parseInt(sheet_data_clean[row][2]);
            i++;
            table_output += '<tr>';
            table_output += '<td>'+row+'<td>';
              table_output += '<td>'+sheet_data_clean[row][1]+'</td>';
              table_output += '<td>'+$num+'</td>';
              table_output += '<td>'+sheet_data_clean[row][3]+'</td>';
              table_output += '<td>'+sheet_data_clean[row][4]+'</td>';
              table_output += '<td>'+sheet_data_clean[row][5]+'</td>';
            table_output += '</tr>';
          }
          document.getElementById('excel_data').innerHTML = table_output;
          excel_file.value = '';
      }
  });
</script>
@endpush

resources/views/dashboard/campaign/detail.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
   <section class="col-lg-6">
    <div class="box">
      <div class="box">
        <div class="box-header">
          <div class="pull-right box-tools">
          </div>
          {{-- <i class="fa fa-file"></i> --}}
          <h3 class="box-title"> Info</h3>
        </div>
        <div class="box-body">
          <div class="col-lg-12">
            <label for="campaign_name" class="col-md-4 control-label">Campaign Name</label>
            <div class="col-md-6">{{ $campaign->campaign_name }}</div>
          </div>     
          <div class="col-lg-12">
            <label for="campaign_name" class="col-md-4 control-label">Total Number Call</label>
            <div class="col-md-6">{{ $total_number }}</div>
          </div> 
          <div class="col-lg-12">
            <label for="campaign_name" class="col-md-4 control-label">Status</label>
            <div class="col-md-6">{{ $campaign->msstatus_id }}</div>
          </div>    
          <div class="col-lg-12">
            <label for="campaign_name" class="col-md-4 control-label">Created By</label>
            <div class="col-md-6">{{ $campaign->user->name }}</div>
          </div>                                              
        </div>
      </div>
    </div>
  </section>
  <section class="col-lg-6">
    <div class="box">
      <div class="box">
        <div class="box-header">
          {{-- <i class="fa fa-file"></i> --}}
          <h3 class="box-title"> Result Campaign</h3>
        </div>
        <div class="box-body">
          <div class="col-lg-12">
            <label for="campaign_name" class="col-md-4 control-label">Date Started</label>
            <div class="col-md-6"></div>
          </div>     
          <div class="col-lg-12">
            <label for="campaign_name" class="col-md-4 control-label">Date Finish</label>
            <div class="col-md-6"></div>
          </div> 
          <div class="col-lg-12">
            <label for="campaign_name" class="col-md-4 control-label">Total Call</label>
            <div class="col-md-6"></div>
          </div>    
          <div class="col-lg-12">
            <label for="campaign_name" class="col-md-4 control-label">Success Call</label>
            <div class="col-md-6"></div>
          </div>  
          <div class="col-lg-12">
            <label for="campaign_name" class="col-md-4 control-label">Failed Call</label>
            <div class="col-md-6"></div>
          </div>                                                       
          <div class="col-lg-12">
            <label for="campaign_name" class="col-md-4 control-label">Campaign Progress %</label>
            <div class="col-md-6"></div>
          </div>                                              
        </div>
      </div>
    </div>
  </section> 
  <section class="col-lg-12 connectedSortable">
    <div class="box">
      <div class="box-header">
        {{-- <i class="fa fa-file"></i> --}}
        <h3 class="box-title"> Detail Call</h3>
      </div>
      <div class="box-body">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="height: 750px; width: 100%;">
          <table id="datatbl" class="table table-hover">
            {{-- <table id="datatbl" class="display"> --}}
            <thead class="thead-dark">
              <tr>
                <th class="text-center">#</th>
                <th class="text-center">Acc ID</th>
                <th class="text-center">Name</th>
                <th class="text-center">Phone</th>
                <th class="text-center">Bill Date</th>
                <th class="text-center">Due Date</th>
                <th class="text-center">Nominal</th>
                <th class="text-center">Call Date</th>
                <th class="text-center">Call Response</th>
                <th class="text-center">Action</th>
              </tr>
            </thead>  
            <tbody>
              @foreach($numbers as $n => $numb)
              <tr>
                <td class="text-center">{{ $n++ }}</td>
                <td class="text-center">{{ $numb->account_id }}</td>
                <td class="text-center">{{ $numb->name }}</td>
                <td class="text-center">{{ $numb->phone }}</td>
                <td class="text-center">{{ $numb->bill_date }}</td>
                <td class="text-center">{{ $numb->due_date }}</td>
                <td class="text-center">{{ $numb->nominal }}</td>
                <td class="text-center">{{ $numb->call_date }}</td>
                <td class="text-center">{{ $numb->response }}</td>
                <td class="text-center"><a href=""><i class="fa fa-eye"></i></a></td>
              </tr>
              @endforeach
            </tbody>
          </table>              
        </div>   
      </div>
    </div>
  </section> 
</div>
@endsection

@push('scripts')
<script>
  $(document).ready(function() {
    var table = $('#datatbl').DataTable( {
        rowReorder: {
            selector: 'td:nth-child(2)'
        },
        responsive: true
    } );
} );
</script>
@endpush

resources/views/dashboard/campaign/index.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
    <section class="col-lg-12 connectedSortable">
      <div class="box">
        <div class="box">
          <div class="box-header">
            <div class="pull-right box-tools">
              <a href="{{ action('CampaignController@create') }}" type="button" class="btn btn-primary btn-sm daterange" data-toggle="tooltip" title="Add new Campaign"><i class="fa fa-sticky-note-o"></i></a>
              <a href="{{ url('campaign') }}" type="button" class="btn btn-primary btn-sm daterange" data-toggle="tooltip" title="Active Campaigns"><i class="fa fa-bell"></i></a>
              <a href="{{ url('campaign/archive') }}" type="button" class="btn btn-primary btn-sm daterange" data-toggle="tooltip" title="Archive Campaigns"><i class="fa fa-archive"></i></a>
              <button type="button" class="btn btn-primary btn-sm" data-widget="collapse" data-toggle="tooltip" title="Collapse" style="margin-right: 5px;"><i class="fa fa-minus"></i></button>
            </div>

            {{-- <i class="fa fa-volume-control-phone"></i> --}}
            <h3 class="box-title">
              {{ $page }}
            </h3>
          </div>
          <div class="box-body">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="">
              <table id="datatbl" class="table table-hover">
                <thead class="thead-dark">
                  <tr>
                    {{-- <th class="text-center">No</th> --}}
                    <th class="text-center">Action</th>
                    <th class="text-center">Name(s)</th>
                    <th class="text-center">Date/Time</th>
                    <th class="text-center">Total Data</th>
                    <th class="text-center">Status</th>
                    <th class="text-center">Created By</th>
                  </tr>
                </thead>  
                <tbody>
                  @foreach ($campaign as $c => $camp)
                  <tr>
                    {{-- <td class="text-center">{{ $c++ }}</td> --}}
                    <td class="text-center">
                      {{-- <a href="#"><i class="fa fa-play-circle" title="Play/Stop Campaign"></i></a>  --}}

                      {{-- <a href="{{ action('CampaignController@destroy', $camp->id ) }}"><i class="fa fa-trash" title="Delete"></i></a>    --}}
                      <form action="{{ route('campaign.destroy' , $camp->id)}}" method="POST" class="d-inline">
                        <input name="_method" type="hidden" value="DELETE">
                        {{ csrf_field() }}
                          <a href="{{ action('CampaignController@show', $camp->id)}}" class="btn btn-xs btn-info"><i class="fa fa-eye" title="Show"></i></a>
                          <a href="{{ action('CampaignController@edit', $camp->id ) }}" class="btn btn-xs btn-primary"><i class="fa fa-edit" title="Edit"></i></a>   
                          <button type="submit" class="btn btn-xs btn-warning" name="activebtn" value="{{ $camp->msstatus_id }}" title="Deactivated campaign">
                            <i class="fa fa-times"></i>                                
                          </button>
                      </form>
                    </td>         
                    <td class="text-center">{{ $camp->campaign_name }}</td>
                    <td class="text-center">{{ date('d M Y', strtotime($camp->created_at)) }}</td>
                    <td class="text-center">{{ $camp->qty }}</td>
                    <td class="text-center"><strong></strong></td>
                    <td class="text-center">{{ $camp->user->name }}</td>
                  </tr>
                  @endforeach
                </tbody>
              </table>              
            </div>              
          </div>
        </div>
      </div>
    </section>
    {{-- <section class="col-lg-4 connectedSortable" id="detail">
      <div class="box">
        <div class="box">
          <div class="box-header">
            <i class="fa fa-info-circle"></i>

            <h3 class="box-title">
              Detail
            </h3>
          </div>
          <div class="box-body">
            <p id="detail">This is a paragraph.</p>
            <button id="btndetail">Toggle between hide() and show()</button>
          </div>
        </div>
      </div>
    </section>     --}}
  </div>
@endsection

@push('scripts')
<script>
  $(document).ready(function() {
    var table = $('#datatbl').DataTable( {
        rowReorder: {
            selector: 'td:nth-child(2)'
        },
        responsive: true
    } );
} );
</script>
@endpush